/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PromptDialog.java
 *
 * Created on May 30, 2011, 11:09:23 PM
 */
package amt.alc;

import amt.graph.GraphCanvas;
import amt.log.Logger;
import java.util.Enumeration;
import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author zpwn
 */
public class PromptDialog extends javax.swing.JDialog {

  private boolean submit = false;
  private final String[] question_keywords = {"Interest:interested", "Excitement:excited", "Confidence:confident", "Frustration:frustrated"};
  private Random rand = new Random();
  private int random_number = -1;
  private Logger logger = Logger.getLogger();
  private String logmsg = "";
  private GraphCanvas gc=null;

  /** Creates new form PromptDialog */
  public PromptDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        submitBtn = new javax.swing.JButton();
        rbtn_1 = new javax.swing.JRadioButton();
        question_Label = new javax.swing.JLabel();
        rbtn_2 = new javax.swing.JRadioButton();
        rbtn_3 = new javax.swing.JRadioButton();
        rbtn_4 = new javax.swing.JRadioButton();
        rbtn_5 = new javax.swing.JRadioButton();

        buttonGroup.add(rbtn_1);
        buttonGroup.add(rbtn_2);
        buttonGroup.add(rbtn_3);
        buttonGroup.add(rbtn_4);
        buttonGroup.add(rbtn_5);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Expression");
        setAlwaysOnTop(true);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setName("promptdialog"); // NOI18N
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        rbtn_1.setText("least");
        rbtn_1.setName("1"); // NOI18N

        question_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        random_number = rand.nextInt(4);
        String[] keywords=question_keywords[random_number].split(":");

        String question = "<html><span style='font-weight:900;font-size:14;'>"+keywords[0] +"!</span> How "+keywords[1]+" are you feeling right now?</html>";
        question_Label.setText(question);
        question_Label.setFocusable(false);
        question_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rbtn_2.setText("less");
        rbtn_2.setName("2"); // NOI18N

        rbtn_3.setText("neutral");
        rbtn_3.setName("3"); // NOI18N

        rbtn_4.setText("somewhat");
        rbtn_4.setName("4"); // NOI18N

        rbtn_5.setText("very");
        rbtn_5.setName("5"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtn_1)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_2)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_3)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_4)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(submitBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(question_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_1)
                    .addComponent(rbtn_2)
                    .addComponent(rbtn_3)
                    .addComponent(rbtn_4)
                    .addComponent(rbtn_5))
                .addGap(18, 18, 18)
                .addComponent(submitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
    // TODO add your handling code here:
    JRadioButton radioBtn = getSelection(buttonGroup);
    try {
      logmsg = "Student is "+radioBtn.getText()+" "+question_keywords[random_number];
      System.out.println(logmsg);
      logger.concatOut(Logger.ACTIVITY, "PromptDialog.submitBtnActionPerformed.1",logmsg);
      this.dispose();
      submit = true;
      if(gc!=null)
      {        
        
        gc.getCover().getMenuBar().doneAction();
      }
      else
        System.out.println("GC NULL");
      
    } catch (NullPointerException npe) {
    }
  }//GEN-LAST:event_submitBtnActionPerformed
  public boolean isSubmit() {
    return submit;
  }
  public void setGC(GraphCanvas gc)
  {
    this.gc = gc;
  }
  public GraphCanvas getGC()
  {
    return this.gc;
  }
//  public String LogMsg()
//  {
//    return logmsg;
//  }

  // This method returns the selected radio button in a button group
  public JRadioButton getSelection(ButtonGroup group) {
    for (Enumeration e = group.getElements(); e.hasMoreElements();) {
      JRadioButton b = (JRadioButton) e.nextElement();
      if (b.getModel() == group.getSelection()) {
        return b;
      }
    }
    return null;
  }

  /**
   * @param args the command line arguments
   */
  public void popup() {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        addWindowListener(new java.awt.event.WindowAdapter() {

          public void windowClosing(java.awt.event.WindowEvent e) {
          }
        });
        setVisible(true);
        pack();
      }
    });
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel question_Label;
    private javax.swing.JRadioButton rbtn_1;
    private javax.swing.JRadioButton rbtn_2;
    private javax.swing.JRadioButton rbtn_3;
    private javax.swing.JRadioButton rbtn_4;
    private javax.swing.JRadioButton rbtn_5;
    public javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
